version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/lt-mvp-webapp
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: aws-bin/app-stop.sh
      timeout: 10
      runas: ec2-user
  BeforeInstall:
    - location: aws-bin/before-install.sh
      timeout: 10
      runas: ec2-user
  AfterInstall:
    - location: aws-bin/install-pkgs.sh
      timeout: 1200
      runas: ec2-user
  ApplicationStart:
    - location: aws-bin/app-start.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: aws-bin/app-validate.sh
      timeout: 10
      runas: ec2-user
