version: 2
jobs:
  build:
    working_directory: ~/lt-mvp-webapp
    docker:
      - image: davd33/circleci2:0.1
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t lt-mvp-webapp:$TAG .
          ./deploy.sh
